### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cburkert** [SNTSVV/MoLFI#2]
Please add a license declaration to this repo. This way other developers (including myself) know if and how they can extend or incorporate your code, which is really cool by the way.

**Comment by salmamess** [comment]
Thanks for pointing this out. We will check with our legal department and get back to you soon.

**Comment by SalmaMessaoudi** [comment]
Thanks for pointing this out. We will check with our legal department and get back to you soon

**Comment by cbarlow6** [comment]
Hi Salma,
Do you have an update on the license declaration?

**Comment by donghwan-shin** [comment]
Thanks, the license is finally added: a723483e8afa6b2fdeaefa4d75f718e96ea3278b.

**Comment by cbarlow6** [comment]
> Thanks, the license is finally added: [a723483](https://github.com/SNTSVV/MoLFI/commit/a723483e8afa6b2fdeaefa4d75f718e96ea3278b).

Thank you!
